name: Acquire Unity License

on:
  workflow_dispatch: {}

jobs:
  activation:
    name: Request Activation File
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Request Manual Activation File
        id: getManualLicenseFile
        uses: game-ci/unity-request-activation-file@v2
        with:
          unityVersion: 2022.3.2f1

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Unity_v2022.3.2f1.alf
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}
